### ISSUE TITLE
LOOP

### ISSUE THREAD

**Issue by Ren9111** [eu-digital-green-certificates/dgca-issuance-web#153] opened 2022-01-04 20:45 UTC
![image](https://user-images.githubusercontent.com/27509049/148121753-33cd1459-858b-41d3-b7b6-173e3c5269ce.png)

**Comment by daniel-eder** [comment] 2022-01-10 07:28
Duplicate of https://github.com/eu-digital-green-certificates/dgca-issuance-web/issues/149

**Closed by daniel-eder** 2022-01-10 07:28 UTC
Labels: question
